### ISSUE TITLE
Does not compile as dependency?

### ISSUE THREAD

**Issue by futile** [Nilirad/bevy_prototype_lyon#89]
~~Does this project work with bevy 0.5? It seems bevy's "main"-branch is being tracked, but doing~~

```toml
[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_prototype_lyon = { git = "https://github.com/Nilirad/bevy_prototype_lyon.git", branch = "master" }
```

~~throws compilation errors inside `bevy_prototype_lyon` for me.~~

~~Edit: Current `master` commit when I tried this: 5c92ee50125e526e6af18c2ab913dd2581fdeded~~

Edit: The errors can be reproduced by leaving out the `bevy` dependency, so just running `cargo new` and adding

```toml
[dependencies]
bevy_prototype_lyon = { git = "https://github.com/Nilirad/bevy_prototype_lyon.git", branch = "master" }
```

at commit 5c92ee50125e526e6af18c2ab913dd2581fdeded already causes the `bevy_prototype_lyon` crate to not compile.

All of this is on windows btw.,  cargo & rust versions:

```
cargo 1.52.0-nightly (90691f2bf 2021-03-16)
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
```

But I also tried stable 1.51., which also failed.

```
cargo 1.51.0 (43b129a20 2021-03-16)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**However**, when cloning this repo (at the same commit), `cargo build` as well as `cargo check` both work.

**Comment by futile** [comment]
@Gregoor just saw that you liked the issue; are you also running into this problem? Maybe also on windows or another OS?

**Comment by Gregoor** [comment]
Yes I am, on MacOS and with the same Rust and bevy versions as the ones you tried.

**Comment by futile** [comment]
@Gregoor thanks!

**Comment by nside** [comment]
Simply remove the `default-features = false` in this project Cargo.toml to fix it

**Comment by futile** [comment]
@nside thanks, awesome! Do you know why this fixes the issue, i.e., why the project compiles fine when not used as a dependency, but fails as soon as it is used as a dependency of another crate?

**Comment by nside** [comment]
the bevy_renderer isn't compiled when default flags aren't set. the `dev-dependencies` is different for some reason I'm not aware of

**Comment by Nilirad** [comment]
#90 has been merged, but I did a little bit of changes afterwards. Can you confirm it works with the new version (`bevy_prototype_lyon v0.3.0`)?

**Comment by futile** [comment]
> #90 has been merged, but I did a little bit of changes afterwards. Can you confirm it works with the new version (`bevy_prototype_lyon v0.3.0`)?

@Nilirad Yup, works now, thanks! :)
