### ISSUE TITLE
Version 0.3 does not work with bevy 0.5

### ISSUE THREAD

**Issue by rparrett** [Nilirad/bevy_prototype_lyon#95]
cargo.toml
```[dependencies]
bevy = "0.5"
bevy_prototype_lyon = "0.3"
```
main.rs
```
use bevy::prelude::*;
use bevy_prototype_lyon::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_plugins(ShapePlugin)
        .run();
}
```
cargo run (edit: oops, previous text had wrong error here)
```
    Compiling delete-me v0.1.0 (/Users/robparrett/src/delete-me)
error[E0277]: the trait bound `bevy_prototype_lyon::plugin::ShapePlugin: bevy::prelude::PluginGroup` is not satisfied
 --> src/main.rs:7:22
  |
7 |         .add_plugins(ShapePlugin)
  |                      ^^^^^^^^^^^ the trait `bevy::prelude::PluginGroup` is not implemented for `bevy_prototype_lyon::plugin::ShapePlugin`

error: aborting due to previous error
```

This is due to version 0.3 depending on a git version of bevy instead of the crates.io 0.5 release.

**Comment by rparrett** [comment]
Sorry for the tone here. Some "I just want to draw a line in this game engine" frustration is leaking through. Really appreciate this crate attempting to fill that gap.

**Comment by linevych** [comment]
Compiler already told you where the problem is:

```
error[E0425]: cannot find value `ShapesPlugin` in this scope
  --> src/main.rs:7:22
   |
7  |         .add_plugins(ShapesPlugin) 
   |                      ^^^^^^^^^^^^ help: a unit struct with a similar name exists: `ShapePlugin`
```

It's ShapePlugin not Shape*s*Plugin.

**Comment by rparrett** [comment]
Oops, copy/pasted the wrong compiler error. I did indeed make that typo at one point.

```
   Compiling delete-me v0.1.0 (/Users/robparrett/src/delete-me)
error[E0277]: the trait bound `bevy_prototype_lyon::plugin::ShapePlugin: bevy::prelude::PluginGroup` is not satisfied
 --> src/main.rs:7:22
  |
7 |         .add_plugins(ShapePlugin)
  |                      ^^^^^^^^^^^ the trait `bevy::prelude::PluginGroup` is not implemented for `bevy_prototype_lyon::plugin::ShapePlugin`

error: aborting due to previous error
```

**Comment by rparrett** [comment]
`cargo clean` sorted me out though.

I see now that the version of `bevy_prototype_lyon` uploaded to crates.io depends on `version = "0.5"`. And that maybe it's not even possible to deploy a crate with git dependencies.

Sorry for the noise!

**Comment by linevych** [comment]
I think it's a multiple beavy versions issue. From what I understand it happens when you are using some package which uses different bevy version in it's `Cargo.toml`. You might want to look at the [patching dependencies](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section), I haven't done it myself but this what smart people from [Bevy discord](https://discord.gg/DBR7JBrk) use.

**Comment by rparrett** [comment]
That is what I assumed when I saw that the tagged release of this crate depended in bevy via git, but it must have just been some sort of local cargo issue or something.

**Comment by linevych** [comment]
This release [does not depend on bevy via git](https://github.com/Nilirad/bevy_prototype_lyon/blob/v0.3.0/Cargo.toml#L16).

You can this in your Cargo.lock:

```
[patch."https://github.com/bevyengine/bevy"]
bevy ="0.5.0"
```

**Comment by rparrett** [comment]
Okay so I am just an all around confused fellow. Where does that commit even live?

I'm no longer having any issues though, so no worries there. `cargo clean` sorted me out as I mentioned earlier.

**Comment by linevych** [comment]
You were probably looking at `master`, not at 0.3 tag ;)
